# POST http://localhost:3000/api/auth/register
# Content-Type: application/json

# {
# "email":"arismoratalla@gmail.com",
# "password":"12345678",
# "firstName":"Aris",
# "lastName":"Moratalla",
# "role":"admin"
# }

# POST http://192.168.0.6:3000/api/auth/login
# Content-Type: application/json

# {
# "email":"arismoratalla@gmail.com",
# "password":"12345678"
# }

GET http://172.16.110.78:3001/api/hrmis/nightowls
# GET http://localhost:3001/api/hrmis/earlybirds